"""CPU authority and GGUF intake gates for TurboQuant ``TQ3_4S`` (type 46).

The fixtures are literal bytes derived from ``turbo-tan/llama.cpp-tq3`` rather than
generated by the implementation under test.  That keeps centroid, E3M5, 3-bit packing,
sign and WHT mistakes independently observable before any CUDA dispatch is enabled.
"""

from __future__ import annotations

import math
import struct
from pathlib import Path

import torch

from freetoken.models.gguf.dequant import (
    BLOCK_SHAPE,
    DEQUANT_TYPES,
    GGML_NAME,
    GGML_TQ3_4S,
    MMQ_TYPES,
    MMVQ_TYPES,
    MOE_MMQ_TYPES,
    MOE_VEC_TYPES,
    decode_tq3_e3m5,
    dequant_tq3_4s,
    row_bytes,
)


TQ3_CENTROIDS = (
    -1.996684,
    -1.291398,
    -0.740341,
    -0.247508,
    0.230106,
    0.725222,
    1.277503,
    1.988943,
)


def _pack_same_index(index: int) -> bytes:
    """Eight copies of one 3-bit index in the fork's 24-bit subgroup layout."""
    packed = sum(index << (3 * lane) for lane in range(8))
    return packed.to_bytes(3, "little")


def _write_tq3_gguf(path: Path, block: bytes) -> None:
    """One-row GGUF written without gguf-py, whose installed enum intentionally lacks 46."""
    assert len(block) == 16

    def u32(value: int) -> bytes:
        return struct.pack("<I", value)

    def u64(value: int) -> bytes:
        return struct.pack("<Q", value)

    def string(value: str) -> bytes:
        raw = value.encode()
        return u64(len(raw)) + raw

    # v3, one tensor, no KV pairs. Tensor info: name, one dim of 32 values,
    # raw GGML type 46, byte offset zero. Tensor data starts at the default 32B alignment.
    body = b"GGUF" + u32(3) + u64(1) + u64(0)
    body += string("weight") + u32(1) + u64(32) + u32(46) + u64(0)
    body += b"\0" * (-len(body) % 32)
    body += block
    path.write_bytes(body)


def test_tq3_4s_type_geometry_advertises_dequant_and_dense_mmvq_only():
    assert GGML_TQ3_4S == 46
    assert GGML_NAME[GGML_TQ3_4S] == "TQ3_4S"
    assert BLOCK_SHAPE[GGML_TQ3_4S] == (32, 16)
    assert row_bytes(32, GGML_TQ3_4S) == 16
    assert row_bytes(2048, GGML_TQ3_4S) == 1024

    # Exact materialized CUDA and dense small-batch MMVQ have parity gates. MMQ
    # and fused-MoE remain unavailable until their own staged tests land.
    assert GGML_TQ3_4S in DEQUANT_TYPES
    assert GGML_TQ3_4S in MMVQ_TYPES
    for capability in (MMQ_TYPES, MOE_VEC_TYPES, MOE_MMQ_TYPES):
        assert GGML_TQ3_4S not in capability


def test_tq3_4s_c_header_has_the_exact_16_byte_block_contract():
    header = (
        Path(__file__).parents[2]
        / "python/freetoken/kernel/csrc/gguf/ggml-common.h"
    ).read_text()
    assert "#define QK_TQ3_0 32" in header
    assert "uint8_t d[4]" in header
    assert "uint8_t qs[QK_TQ3_0 * 3 / 8]" in header
    assert "block_tq3_4s" in header
    assert BLOCK_SHAPE[GGML_TQ3_4S][1] == 4 + 32 * 3 // 8


def test_e3m5_literal_decode_table():
    encoded = torch.tensor(
        [0x00, 0x20, 0x3F, 0x40, 0x5F, 0x60, 0x7F, 0x80, 0xFF],
        dtype=torch.uint8,
    )
    expected = torch.tensor(
        [
            0.0,
            0.00390625,
            0.0076904296875,
            0.0078125,
            0.015380859375,
            0.015625,
            0.03076171875,
            0.03125,
            0.4921875,
        ],
        dtype=torch.float32,
    )
    torch.testing.assert_close(decode_tq3_e3m5(encoded), expected, rtol=0, atol=0)


def test_literal_index_ramp_decodes_through_inverse_signed_wht():
    # 0x88c6fa is exactly indices [0,1,2,3,4,5,6,7]. Four identical groups at
    # scale 0x60 (1/64) make the final 24 WHT outputs zero, a useful ordering sentinel.
    raw = torch.tensor(
        list(bytes.fromhex("60 60 60 60 88 c6 fa 88 c6 fa 88 c6 fa 88 c6 fa")),
        dtype=torch.uint8,
    )
    expected = torch.tensor(
        [
            -0.000598356,
            0.026568156,
            -0.050948712,
            -0.000042769,
            -0.093887263,
            0.000093217,
            -0.000120263,
            -0.004737361,
            *([0.0] * 24),
        ],
        dtype=torch.float32,
    )
    torch.testing.assert_close(dequant_tq3_4s(raw, torch.float32), expected, rtol=2e-5, atol=2e-7)


def test_centroid_four_discriminator_rejects_the_fast_approximate_codebook():
    # All transformed values are centroid[4]/64. A normalized WHT maps the constant
    # vector to one non-zero coefficient, so this distinguishes the authoritative
    # +0.230106 centroid from the fork's approximate integer-dot codebook.
    raw = torch.tensor(
        [0x60] * 4 + list(_pack_same_index(4)) * 4,
        dtype=torch.uint8,
    )
    expected = torch.zeros(32, dtype=torch.float32)
    expected[0] = math.sqrt(32.0) * TQ3_CENTROIDS[4] / 64.0
    torch.testing.assert_close(dequant_tq3_4s(raw, torch.float32), expected, rtol=2e-6, atol=2e-7)


def test_sm75_dp4a_levels_are_fitted_to_the_authoritative_tq3_4s_codebook():
    donor = torch.tensor([-127, -79, -45, -14, 14, 45, 79, 127], dtype=torch.float64)
    donor *= 2.1519 / 127.0
    fitted = torch.tensor([-113, -73, -42, -14, 13, 41, 72, 112], dtype=torch.float64)
    fitted *= 0.017704291602768495
    exact = torch.tensor(TQ3_CENTROIDS, dtype=torch.float64)

    donor_rmse = torch.sqrt(torch.mean((donor - exact) ** 2))
    fitted_rmse = torch.sqrt(torch.mean((fitted - exact) ** 2))
    assert fitted_rmse.item() < 0.003
    assert donor_rmse.item() / fitted_rmse.item() > 20
    assert torch.max(torch.abs(fitted - exact)).item() < 0.007

    source = (
        Path(__file__).parents[2]
        / "python/freetoken/kernel/csrc/gguf/vecdotq.cuh"
    ).read_text()
    assert "TQ3_4S_LEVELS_LO 0xF2D6B78F" in source
    assert "TQ3_4S_LEVELS_HI 0x7048290D" in source
    assert "TQ3_4S_DP4A_SCALE 0.017704291602768495f" in source


def test_blocks_are_independent_and_output_dtype_is_honored():
    live = bytes([0x60] * 4) + _pack_same_index(4) * 4
    zero = bytes([0x00] * 4) + _pack_same_index(7) * 4
    raw = torch.tensor(list(live + zero), dtype=torch.uint8)

    output = dequant_tq3_4s(raw, torch.bfloat16)

    assert output.shape == (64,)
    assert output.dtype is torch.bfloat16
    assert output[0].float().item() != 0
    assert torch.count_nonzero(output[32:]) == 0


def test_reader_sizes_type_46_when_installed_gguf_py_is_stale(tmp_path: Path):
    import gguf

    from freetoken.models.gguf.reader import iter_gguf_tensors

    # The current test environment is stale, but this must remain green once gguf-py
    # eventually learns type 46 too.
    path = tmp_path / "tiny-tq3.gguf"
    block = bytes([0x60] * 4) + _pack_same_index(4) * 4
    _write_tq3_gguf(path, block)

    [tensor] = list(iter_gguf_tensors(str(path)))
    assert tensor.name == "weight"
    assert tensor.shape == (32,)
    assert tensor.ggml_type == GGML_TQ3_4S
    assert tensor.rows == 1
    assert tensor.row_bytes == 16
    assert tensor.packed().shape == (1, 16)
    assert tensor.packed().flatten().tolist() == list(block)
